# Generated by Django 5.1.6 on 2025-03-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_formfill_isdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfill',
            name='videomodel',
            field=models.FileField(null=True, upload_to='video'),
        ),
    ]
