# Generated by Django 5.1.6 on 2025-03-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_formfill_videomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfill',
            name='imagemodel',
            field=models.FileField(upload_to='images'),
        ),
    ]
