# Generated by Django 5.1.6 on 2025-03-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_formfill_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfill',
            name='isrecycle',
            field=models.BooleanField(default=False),
        ),
    ]
