# Generated by Django 5.1.6 on 2025-03-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_formfill_isrecycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfill',
            name='isrecycle',
        ),
    ]
