# Generated by Django 5.1.6 on 2025-03-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_formfill_isrecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfill',
            name='isdelete2',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
